"""initial_schema

Revision ID: ec28dc49fb6f
Revises: 
Create Date: 2026-05-25 10:57:26.227118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec28dc49fb6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role_global', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('plan_type', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('settings', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('budget_total', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('active_baseline_id', sa.Uuid(), nullable=True),
    sa.Column('pm_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'on_hold', 'completed', 'cancelled')", name='chk_project_status'),
    sa.ForeignKeyConstraint(['pm_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_active_baseline_id'), 'projects', ['active_baseline_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('hourly_rate_dh', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False),
    sa.Column('monthly_capacity_hours', sa.Integer(), server_default='168', nullable=False),
    sa.Column('skills', sa.JSON(), server_default='[]', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_workspace_id'), 'resources', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('ai_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_project_id'), 'ai_insights', ['project_id'], unique=False)
    op.create_table('phases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('wbs_code', sa.String(length=50), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('weight_percent', sa.Numeric(precision=5, scale=2), server_default='0.0', nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_finish', sa.Date(), nullable=True),
    sa.CheckConstraint('weight_percent BETWEEN 0 AND 100', name='chk_phase_weight'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'wbs_code', name='uq_phase_project_wbs')
    )
    op.create_table('project_baselines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('locked_by', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_baselines_is_active'), 'project_baselines', ['is_active'], unique=False)
    op.create_index(op.f('ix_project_baselines_project_id'), 'project_baselines', ['project_id'], unique=False)
    op.create_table('resource_calendars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.CheckConstraint("event_type IN ('holiday', 'leave', 'overtime')", name='chk_calendar_event_type'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'date', name='uq_resource_calendar_date')
    )
    op.create_table('risks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('contingency_threshold', sa.Integer(), server_default='15', nullable=False),
    sa.Column('contingency_factor', sa.Numeric(precision=5, scale=2), server_default='0.15', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'mitigated', 'closed')", name='chk_risk_status'),
    sa.CheckConstraint('impact BETWEEN 1 AND 5', name='chk_risk_impact'),
    sa.CheckConstraint('probability BETWEEN 1 AND 5', name='chk_risk_probability'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risks_critical', 'risks', ['risk_score'], unique=False, postgresql_where="status = 'active'")
    op.create_index(op.f('ix_risks_project_id'), 'risks', ['project_id'], unique=False)
    op.create_index(op.f('ix_risks_risk_score'), 'risks', ['risk_score'], unique=False)
    op.create_index(op.f('ix_risks_status'), 'risks', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phase_id', sa.Uuid(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('wbs_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('duration_days', sa.Integer(), server_default='1', nullable=False),
    sa.Column('start_date_scheduled', sa.Date(), nullable=True),
    sa.Column('end_date_scheduled', sa.Date(), nullable=True),
    sa.Column('early_start', sa.Date(), nullable=True),
    sa.Column('early_finish', sa.Date(), nullable=True),
    sa.Column('late_start', sa.Date(), nullable=True),
    sa.Column('late_finish', sa.Date(), nullable=True),
    sa.Column('total_float', sa.Integer(), server_default='0', nullable=False),
    sa.Column('free_float', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_critical', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_milestone', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('weight_percent', sa.Numeric(precision=5, scale=2), server_default='0.0', nullable=False),
    sa.Column('contingency_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='not_started', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='3', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'completed', 'blocked', 'cancelled')", name='chk_task_status'),
    sa.CheckConstraint('duration_days >= 0', name='chk_task_duration'),
    sa.CheckConstraint('priority BETWEEN 1 AND 5', name='chk_task_priority'),
    sa.CheckConstraint('weight_percent BETWEEN 0 AND 100', name='chk_task_weight'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_critical', 'tasks', ['is_critical'], unique=False, postgresql_where='is_critical = true')
    op.create_index('idx_tasks_dates', 'tasks', ['start_date_scheduled', 'end_date_scheduled'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('deliverables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'in_review', 'approved', 'rejected')", name='chk_deliverable_status'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverables_status'), 'deliverables', ['status'], unique=False)
    op.create_index(op.f('ix_deliverables_task_id'), 'deliverables', ['task_id'], unique=False)
    op.create_table('progress_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('physical_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False),
    sa.Column('actual_cost_dh', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=False),
    sa.Column('logged_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('actual_cost_dh >= 0', name='chk_progress_cost'),
    sa.CheckConstraint('actual_hours >= 0', name='chk_progress_hours'),
    sa.CheckConstraint('physical_percent BETWEEN 0 AND 100', name='chk_progress_percent'),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'log_date', name='uq_progress_task_date')
    )
    op.create_index(op.f('ix_progress_logs_task_id'), 'progress_logs', ['task_id'], unique=False)
    op.create_table('risk_task_links',
    sa.Column('risk_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('risk_id', 'task_id')
    )
    op.create_table('task_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_percent', sa.Numeric(precision=5, scale=2), server_default='100.0', nullable=False),
    sa.Column('planned_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('allocation_percent BETWEEN 0 AND 100', name='chk_assignment_allocation'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'resource_id', name='uq_task_assignment')
    )
    op.create_table('task_dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('predecessor_task_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_type', sa.String(length=2), server_default='FS', nullable=False),
    sa.Column('lag_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("dependency_type IN ('FS', 'SS', 'FF', 'SF')", name='chk_dependency_type'),
    sa.CheckConstraint('task_id <> predecessor_task_id', name='chk_no_self_dependency'),
    sa.ForeignKeyConstraint(['predecessor_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'predecessor_task_id', name='uq_task_dependency')
    )
    op.create_index(op.f('ix_task_dependencies_predecessor_task_id'), 'task_dependencies', ['predecessor_task_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_task_id'), 'task_dependencies', ['task_id'], unique=False)
    op.create_table('deliverable_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deliverable_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverable_events_deliverable_id'), 'deliverable_events', ['deliverable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliverable_events_deliverable_id'), table_name='deliverable_events')
    op.drop_table('deliverable_events')
    op.drop_index(op.f('ix_task_dependencies_task_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_predecessor_task_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_table('task_assignments')
    op.drop_table('risk_task_links')
    op.drop_index(op.f('ix_progress_logs_task_id'), table_name='progress_logs')
    op.drop_table('progress_logs')
    op.drop_index(op.f('ix_deliverables_task_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_status'), table_name='deliverables')
    op.drop_table('deliverables')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index('idx_tasks_dates', table_name='tasks')
    op.drop_index('idx_tasks_critical', table_name='tasks', postgresql_where='is_critical = true')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_risks_status'), table_name='risks')
    op.drop_index(op.f('ix_risks_risk_score'), table_name='risks')
    op.drop_index(op.f('ix_risks_project_id'), table_name='risks')
    op.drop_index('idx_risks_critical', table_name='risks', postgresql_where="status = 'active'")
    op.drop_table('risks')
    op.drop_table('resource_calendars')
    op.drop_index(op.f('ix_project_baselines_project_id'), table_name='project_baselines')
    op.drop_index(op.f('ix_project_baselines_is_active'), table_name='project_baselines')
    op.drop_table('project_baselines')
    op.drop_table('phases')
    op.drop_index(op.f('ix_ai_insights_project_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_resources_workspace_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_active_baseline_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
