"""AI Audit Simulation Script for NEXUS V3.

Simulates triggering an AI audit on the UAT project.
Verifies LLMService logic and Fallback report generation.
"""

from __future__ import annotations

import asyncio
import uuid
import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import async_session_factory
from app.domain.models.project import Project
from app.domain.services.llm_service import LLMService

logger = structlog.get_logger(__name__)

async def run_ai_audit_test():
    async with async_session_factory() as db:
        # 1. Fetch the UAT project
        result = await db.execute(select(Project).limit(1))
        project = result.scalar_one_or_none()
        
        if not project:
            print("❌ No project found. Please run seed_uat.py first.")
            return

        print(f"🔍 Starting AI Audit for project: {project.name} ({project.id})")
        
        # 2. Trigger Audit
        llm_service = LLMService(db)
        
        try:
            # This will attempt to call the API configured in .env (ollama)
            # If it fails, it should return the fallback markdown.
            audit_report = await llm_service.generate_project_audit(
                project_id=project.id,
                triggered_by=project.pm_user_id
            )
            
            print("\n" + "="*50)
            print("📄 NEXUS AI AUDIT REPORT (PREVIEW)")
            print("="*50)
            print(audit_report[:1000] + "...") # Show start of report
            print("="*50)
            print("\n✅ AI Audit simulation completed successfully.")
            
            if "AI Audit Offline Fallback Mode" in audit_report:
                print("ℹ️ Note: Report generated using LOCAL FALLBACK engine (LLM API unreachable).")
            else:
                print("🚀 Success: Report generated by REMOTE LLM provider.")
                
        except Exception as e:
            print(f"❌ AI Audit failed: {e}")

if __name__ == "__main__":
    asyncio.run(run_ai_audit_test())
